S5_1&2_TGP/T_G_P/config/routes.rb
Rails.application.routes.draw do

  get 'cities/index'
  get 'cities/show'
  root 'welcome#index'
=begin
  get '/accueil', to: 'accueil#index'
  get 'gossips/:gossip_id', to: 'gossips#index', as: 'gossips_goss_id'
  get '/team', to: 'team#index'
  get '/contact', to: 'contact#index'
  get '/gossips/:id', to: 'gossips#index'
  get '/:id', to: 'accueil#index'
  get '/users/:user_id', to: 'users#index', as: 'users_user_id'
=end
  resources :accueil
  resources :gossips
  resources :team
  resources :contact
  resources :users
  resources :city
  resources :gossips do resources :comments end
  resources :session
end

S5_1&2_TGP/T_G_P/app/models/add_colomn.rb
class AddColomn < ApplicationRecord
end

S5_1&2_TGP/T_G_P/app/models/add_colomn_comment.rb
class AddColomnComment < ApplicationRecord
end

S5_1&2_TGP/T_G_P/app/models/add_colomn_user.rb
class AddColomnUser < ApplicationRecord
end

S5_1&2_TGP/T_G_P/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

S5_1&2_TGP/T_G_P/app/models/city.rb
class City < ApplicationRecord
has_many :users
end

S5_1&2_TGP/T_G_P/app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :gossip
end

S5_1&2_TGP/T_G_P/app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, presence: true, length: {in: 3..14}
	validates :content, presence: true
	has_many :tags
	has_many :comments
	has_many :likes
	belongs_to :user
end

S5_1&2_TGP/T_G_P/app/models/like.rb
class Like < ApplicationRecord

	belongs_to :user, optional: true
	has_many :gossips
	
end

S5_1&2_TGP/T_G_P/app/models/private_message.rb
class PrivateMessage < ApplicationRecord

	belongs_to :user, optional: true
	has_many :user

end

S5_1&2_TGP/T_G_P/app/models/tag.rb
class Tag < ApplicationRecord
has_many :gossips
end

S5_1&2_TGP/T_G_P/app/models/user.rb
class User < ApplicationRecord
	validates :password, presence: true, length: { minimum: 6 }
	has_many :comments
	has_many :gossips
	has_many :likes
	has_many :private_messages
	belongs_to :city
	has_secure_password

end

S5_1&2_TGP/T_G_P/app/controllers/accueils_controller.rb
class AccueilController < ApplicationController
	def index
		if session[:user_id] == nil
			redirect_to root_path
		else
			@user = User.find(session[:user_id])
		end
	end
end

S5_1&2_TGP/T_G_P/app/helpers/accueils_helper.rb
module AccueilsHelper
end

S5_1&2_TGP/T_G_P/app/helpers/application_helper.rb
module ApplicationHelper
end

S5_1&2_TGP/T_G_P/app/helpers/cities_helper.rb
module CitiesHelper
end

S5_1&2_TGP/T_G_P/app/helpers/comments_helper.rb
module CommentsHelper
end

S5_1&2_TGP/T_G_P/app/helpers/contacts_helper.rb
module ContactsHelper
end

S5_1&2_TGP/T_G_P/app/helpers/gossips_helper.rb
module GossipsHelper
end

S5_1&2_TGP/T_G_P/app/helpers/session_helper.rb
module SessionHelper
end

S5_1&2_TGP/T_G_P/app/helpers/teams_helper.rb
module TeamsHelper
end

S5_1&2_TGP/T_G_P/app/helpers/users_helper.rb
module UsersHelper
end

S5_1&2_TGP/T_G_P/app/helpers/welcome_helper.rb
module WelcomeHelper
end

S5_1&2_TGP/T_G_P/app/views/accueils/index.html.erb
<h1>Accueils#index</h1>
<p>Find me in app/views/accueils/index.html.erb</p>
<!DOCTYPE html>
<html>
<head>
	<title>Accueil</title>
</head>


<body>
  <%= link_to "Se déconnecter", session_path(session.id), method: :delete %>
	<h1 class='titre'> Bienvenue <%= User.find_by(id: session[:user_id]).first_name %> !</h1>
		<br>

		<p> Bienvenue sur la page d'accueil !</p>
		<br>
		<h3><%= link_to "Creat gossip", new_gossip_path%></h3><br>
		
            
            

  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">Messages</a></li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group input-group">
          <input type="text" class="form-control" placeholder="Search..">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">
              <span class="glyphicon glyphicon-search"></span>
            </button>
          </span>        
        </div>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> My Account</a></li>
      </ul>
    </div>
  </div>
</nav>
  
<div class="container text-center">    
  <div class="row">
    <div class="col-sm-3 well">
      <div class="well">
        <p><a href="#">My Profile</a></p>
        <%= image_tag "bird.jpg", alt:"Profile" , width: 55 , height: 55 %>
      </div>
      <div class="well">
        <p><a href="#">Interests</a></p>
        <p>
          <span class="label label-default">News</span>
          <span class="label label-primary">W3Schools</span>
          <span class="label label-success">Labels</span>
          <span class="label label-info">Football</span>
          <span class="label label-warning">Gaming</span>
          <span class="label label-danger">Friends</span>
        </p>
      </div>
      <div class="alert alert-success fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
        <p><strong>Ey!</strong></p>
          People are looking at your profile. Find out who.
      </div>
        <p><a href="#">Link</a></p>
        <p><a href="#">Link</a></p>
        <p><a href="#">Link</a></p>
    </div>
    <div class="col-sm-7">
    
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default text-left">
            <div class="panel-body">
              <p contenteditable="true">Status: Feeling Blue</p>
              <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-thumbs-up"></span> Like
              </button>     
            </div>
          </div>
        </div>
      </div>
                   <% @user.gossips.each do |gossip| %>

      <div class="row">
        <div class="col-sm-3">
          <div class="well">
           <p><p><%= gossip.user.first_name %></p></p>
           <%= image_tag "avatar.png", alt:"Profile" , width: 55 , height: 55 %>
          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <p><%= gossip.title %></p><br>
            <a class="btn btn-primary btn-lg" <%= link_to "Look »", gossip_path(gossip), role: "button"%>></a>   <a class="btn btn-primary btn-lg" <%= link_to "Edit »", edit_gossip_path(gossip), role: "button"%>></a>    <a class="btn btn-primary btn-lg" href = '/gossips/<%=gossip.id%>' data-method="delete" data-confirm="t'es sure?" role = "button">Supr »</a>
          </div>
        </div>
      </div>
                      <% end %>

          </div>
    <div class="col-sm-2 well">
      <div class="thumbnail">
        <p>Upcoming Events:</p>
        <%= image_tag "snowy-mountain.jpg" , alt:"Tana" , width: 400 , height: 300 %>
        <p><strong>Tana</strong></p>
        <p><%=Time.now.strftime("%d/%m/%Y")%></p>
        <button class="btn btn-primary">Info</button>
      </div>      
      <div class="well">
        <p>ADS</p>
      </div>
      <div class="well">
        <p>ADS</p>
      </div>
    </div>
  </div>
</div>

<footer class="container-fluid text-center">
  <p>Thank you</p>
</footer>


 </body>


</html>s