S5_1&2_TGP/T_G_P/config/routes.rb
Rails.application.routes.draw do

  get 'cities/index'
  get 'cities/show'
  root 'welcome#index'
=begin
  get '/accueil', to: 'accueil#index'
  get 'gossips/:gossip_id', to: 'gossips#index', as: 'gossips_goss_id'
  get '/team', to: 'team#index'
  get '/contact', to: 'contact#index'
  get '/gossips/:id', to: 'gossips#index'
  get '/:id', to: 'accueil#index'
  get '/users/:user_id', to: 'users#index', as: 'users_user_id'
=end
  resources :accueil
  resources :gossips
  resources :team
  resources :contact
  resources :users
  resources :city
  resources :gossips do resources :comments end
  resources :session
end

S5_1&2_TGP/T_G_P/app/models/add_colomn.rb
class AddColomn < ApplicationRecord
end

S5_1&2_TGP/T_G_P/app/models/add_colomn_comment.rb
class AddColomnComment < ApplicationRecord
end

S5_1&2_TGP/T_G_P/app/models/add_colomn_user.rb
class AddColomnUser < ApplicationRecord
end

S5_1&2_TGP/T_G_P/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

S5_1&2_TGP/T_G_P/app/models/city.rb
class City < ApplicationRecord
has_many :users
end

S5_1&2_TGP/T_G_P/app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :gossip
end

S5_1&2_TGP/T_G_P/app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, presence: true, length: {in: 3..14}
	validates :content, presence: true
	has_many :tags
	has_many :comments
	has_many :likes
	belongs_to :user
end

S5_1&2_TGP/T_G_P/app/models/like.rb
class Like < ApplicationRecord

	belongs_to :user, optional: true
	has_many :gossips
	
end

S5_1&2_TGP/T_G_P/app/models/private_message.rb
class PrivateMessage < ApplicationRecord

	belongs_to :user, optional: true
	has_many :user

end

S5_1&2_TGP/T_G_P/app/models/tag.rb
class Tag < ApplicationRecord
has_many :gossips
end

S5_1&2_TGP/T_G_P/app/models/user.rb
class User < ApplicationRecord
	validates :password, presence: true, length: { minimum: 6 }
	has_many :comments
	has_many :gossips
	has_many :likes
	has_many :private_messages
	belongs_to :city
	has_secure_password

end

S5_1&2_TGP/T_G_P/app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
    @gossip = Gossip.find(params[:gossip_id])
  end

  def show
      # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
     @gossip = Gossip.find(params[:id])
  end

  def new
      # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
      @gossip = Gossip.new

  end

  def create
      # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
      # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
      # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
       @gossip = Gossip.new(title: params[:title], content: params[:content]) # avec xxx qui sont les données obtenues à partir du formulaire
       @gossip.user = User.find_by(id: session[:user_id])
      if @gossip.save # essaie de sauvegarder en base @gossip
        # si ça marche, il redirige vers la page d'index du site
        redirect_to accueil_index_path
      else
        # sinon, il render la view new (qui est celle sur laquelle on est déjà)
        render :new
      end
  end

  def edit
      # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
      @gossip = Gossip.find(params[:id ])
  end

  def update
      # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
      # pour info, le contenu de ce formulaire sera accessible dans le hash params
      # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
      @gossip = Gossip.find(params[:id])
  if @gossip.update(title: params[:title], content: params[:content], user_id: 11)
    
    redirect_to gossip_path
  else
    render :edit
  end
  end

  def destroy
      # Méthode qui récupère le potin concerné et le détruit en base
      # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
       @gossip = Gossip.find(params[:id])
       
        if @gossip.comments != nil
          @gossip.comments.each do |s|
        s.destroy
      end
      end
  if @gossip.destroy

    redirect_to accueil_index_path
  else
    render :show
  end

  end
end

S5_1&2_TGP/T_G_P/app/helpers/accueils_helper.rb
module AccueilsHelper
end

S5_1&2_TGP/T_G_P/app/helpers/application_helper.rb
module ApplicationHelper
end

S5_1&2_TGP/T_G_P/app/helpers/cities_helper.rb
module CitiesHelper
end

S5_1&2_TGP/T_G_P/app/helpers/comments_helper.rb
module CommentsHelper
end

S5_1&2_TGP/T_G_P/app/helpers/contacts_helper.rb
module ContactsHelper
end

S5_1&2_TGP/T_G_P/app/helpers/gossips_helper.rb
module GossipsHelper
end

S5_1&2_TGP/T_G_P/app/helpers/session_helper.rb
module SessionHelper
end

S5_1&2_TGP/T_G_P/app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

S5_1&2_TGP/T_G_P/app/helpers/teams_helper.rb
module TeamsHelper
end

S5_1&2_TGP/T_G_P/app/helpers/users_helper.rb
module UsersHelper
end

S5_1&2_TGP/T_G_P/app/helpers/welcome_helper.rb
module WelcomeHelper
end

S5_1&2_TGP/T_G_P/app/views/gossips/create.html.erb
<h1>Gossips#create</h1>
<p>Find me in app/views/gossips/create.html.erb</p>

S5_1&2_TGP/T_G_P/app/views/gossips/destroy.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Gossip Edit</title>


</head>
<body>


<h1 class='titre'> Edit Gossips</h1>

<h3>Formulaire de Gossip</h3>

<div class="container">

  <%= form_tag url_for(action: 'update'), method: "delete" do %>

        <%= label_tag 'Title' %>
        <%= text_field_tag 'title', @gossip.title, placeholder: "#{@gossip.title}" %>
        <br /> <br />

        <%= label_tag 'Content' %>
        <%= text_area_tag 'content', @gossip.content, placeholder: "#{@gossip.content}" %>
        <br /> <br />

        <%= submit_tag "delete" %>

      <% end %>
  <% if @gossip.errors.any? %>
    <p>Nous n'avons pas réussi à modif le potin pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
      <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>
</body>

</html>

S5_1&2_TGP/T_G_P/app/views/gossips/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Gossip Edit</title>


</head>
<body>


<h1 class='titre'> Edit Gossips</h1>

<h3>Formulaire de Gossip</h3>

<div class="container">

  <%= form_tag url_for(action: 'update'), method: "patch" do %>

        <%= label_tag 'Title' %>
        <%= text_field_tag 'title', @gossip.title, placeholder: "#{@gossip.title}" %>
        <br /> <br />

        <%= label_tag 'Content' %>
        <%= text_area_tag 'content', @gossip.content, placeholder: "#{@gossip.content}" %>
        <br /> <br />

        <%= submit_tag "update patch" %>

      <% end %>
  <% if @gossip.errors.any? %>
    <p>Nous n'avons pas réussi à modif le potin pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
      <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>
</body>

</html>

S5_1&2_TGP/T_G_P/app/views/gossips/index.html.erb
<!DOCTYPE html>

<html>
	<head>
		<title>Gossips</title>
	</head>

  <body class="text-align: center">


<div class="card" style="width: 18rem; height: 10rem;">
	<%= image_tag("chuck_norris.jpg", :alt => "chuck norris") %>
  		<div class="card-body">
    		<h5 class="card-title">Title: <%= @gossip.title %></h5>
    		<p class="card-text">Gossip Content: <%= @gossip.content %></p>
   			<%= link_to "#{@gossip.user.first_name}", users_user_id_path(@gossip.user.id) %>
  		</div>
</div>

</body>

</html>

S5_1&2_TGP/T_G_P/app/views/gossips/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Gossip New</title>


</head>
<body>


<h1 class='titre'> Creat Gossips</h1>

<h3>Formulaire de Gossip</h3>

<div class="container">

  <%= form_tag url_for(action: 'create'), method: "post" do %>

        <%= label_tag 'Title' %>
        <%= text_field_tag 'title', @gossip.title, placeholder: "Titre ici..." %>
       

        <%= label_tag 'Content' %>
        <%= text_area_tag 'content', @gossip.content, placeholder: "Ton potin..." %>
        <br /> <br />

        <%= submit_tag "Create Gossip" %>

  <% end %>
  <% if @gossip.errors.any? %>
    <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
      <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>
</body>

</html>

S5_1&2_TGP/T_G_P/app/views/gossips/show.html.erb
<!DOCTYPE html>

<html>
	<head>
		<title>Gossips</title>
	</head>

  <body class="text-align: center">
    <div class="row">
      <div class="col-sm-3">
        <div class="well">
          <div class="card" style="width: 18rem; height: 10rem;">
          	<%= image_tag("chuck_norris.jpg", :alt => "chuck norris") %>
            		<div class="card-body">
              		<h5 class="card-title">Title: <%= @gossip.title %></h5>
              		<p class="card-text">Gossip Content: <%= @gossip.content %></p>
                  <p class="card-text">City user: <%= @gossip.user.city.name %></p>
             			<%= link_to "#{@gossip.user.first_name}", user_path(@gossip.user.id) %>
            		</div>
                <p><a class="btn btn-primary btn-lg" href = '/gossips/<%=@gossip.id%>' data-method="delete" data-confirm="t'es sure?" role = "button">Supr »</a></p>
          </div>
        </div>
      </div>
      

      <div class="col-sm-9">
        <div class="well">
          
          <div class="container">
            <%= form_tag( "/gossips/#{@gossip.id}/comments", method: "post")  do %>
              <%= label_tag 'Commentaire' %>
              <%= text_area_tag 'content',nil, placeholder: "Ton Commentaire..." %>
              <%= submit_tag "Comment" %>
            
            <% end %>
          </div>

          <div class="container">
            <% @gossip.comments.reverse.each do |lo| %>
              <p class="card-text"><%= lo.content %></p>
            <p><a class="btn btn-primary btn-lg" href = '/gossips/<%=@gossip.id%>/comments/<%=lo.id%>' data-method="delete" data-confirm="t'es sure?" role = "button">Supr »</a></p>
            <% end %>
          </div>

        </div>
      </div>

    </div>
  </body>

</html>

S5_1&2_TGP/T_G_P/app/views/gossips/update.html.erb
<h1>Gossips#update</h1>
<p>Find me in app/views/gossips/update.html.erb</p>